title: Aditya Mishra
description: A Personal Page
theme: just-the-doc

url: https://www.adityamishra.in

aux_links:
  Anonymous Feedback: https://www.admonymous.co/aditya-mishra
  Twitter: https://www.x.com/adityamishra
  Substack: https://www.makingroads.com
