title: Aditya Mishra
description: A Personal Page
theme: just-the-docs

url: https://www.adityamishra.in

aux_links:
  LinkedIn: https://www.linkedin.com/in/adityam/
  Twitter: https://www.x.com/adityamishra
  Substack: https://www.makingroads.com
